apiVersion: v1
kind: ConfigMap
metadata:
  name: appsetting-config
  namespace: user-service
data:
  appsettings.json: |
    {
      "GeneralSettings": {
        "ApiName": "User Service",
        "ApiVersion": "v1",
        "ApiDescription": "User Service API"
      },
      "ConnectionStrings": {
        "PostgresDb": "Host=aws-0-ap-southeast-1.pooler.supabase.com; Database=postgres; Username=postgres.cggerynfjmvyretpnrzy; Password=ProjectHealing@1234",
        "MongoDb": "mongodb://localhost:27017",
        "Redis": "redis-11511.c309.us-east-2-1.ec2.redns.redis-cloud.com:11511,password=GcgEaGqb0xQyUqaBUocI14XpTpzMViJO",
        "ElasticSearch": "localhost:6379"
      },
      "JwtSettings": {
        "Secret": "f8f32ffd678c3f71738411850f8af8b1fc3f6b13b60817d86f370e0232fce69bc4b418315c8224c98e8180b84c0f7b12d20ba6545b7a38d6a5e184159d3d9a41",
        "Issuer": "https://localhost.com/",
        "Audience": "https://localhost.com/",
        "ExpiryMinutes": 60,
        "VerificationExpiryMinutes": 15,
        "RefreshTokenExpiryMinutes": 10080
      },
      "SmtpSettings": {
        "Host": "smtp.gmail.com",
        "Port": "587",
        "Username": "healingcommunityfu@gmail.com",
        "Password": "ulvzzxjaiacuwnce",
        "FromEmail": "healingcommunityfu@gmail.com",
        "FromName": "Healing Community"
      },
      "RabbitMq": {
        "Host": "amqp://rabbitmq.rabbitmq.svc.cluster.local",
        "Username": "guest",
        "Password": "guest"
      },
      "Kestrel": {
        "Endpoints": {
          "Http": {
            "Url": "http://*:8080"
          },
          "Grpc": {
            "Url": "http://*:5005",
            "Protocols": "Http2"
          }
        }
      }
    }
