apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: user-service
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: healingcommunity/user-service:latest
          volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          ports:
            - containerPort: 8080
            - containerPort: 5005
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
      volumes:
        - name: config-volume
          configMap:
            name: appsetting-config
