apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: post-service
  labels:
    app: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: healingcommunity/post-service:latest
          ports:
            - containerPort: 8080
            - containerPort: 5005
          volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
      volumes:
        - name: config-volume
          configMap:
            name: appsetting-config
