apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: post-service
spec:
  selector:
    app: post-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
