apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: elastic
  name: elasticsearch-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/elasticsearch"