apiVersion: v1
kind: ConfigMap
metadata:
  name: appsetting-config
  namespace: hook-service
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "Message": "Demo message from configmap"
    }
