apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hook-service
  name: hook-service
  labels:
    app: hook-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hook-service
  template:
    metadata:
      labels:
        app: hook-service
    spec:
      containers:
        - name: hook-service
          image: healingcommunity/hook-service:latest
          volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          ports:
            - containerPort: 8080
      
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
      volumes:
        - name: config-volume
          configMap:
            name: appsetting-config