apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector-service
  namespace: detector-service
  labels:
    app: detector-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detector-service
  template:
    metadata:
      labels:
        app: detector-service
    spec:
      containers:
        - name: detector-service
          image: healingcommunity/detector-service:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
