apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: group-service-hpa
  namespace: group-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: group-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # The target value is the average CPU utilization of all pods in the deployment
          averageUtilization: 70
