apiVersion: v1
kind: Service
metadata:
  name: group-service
  namespace: group-service
spec:
  selector:
    app: group-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 5005
      targetPort: 5005
  type: ClusterIP
