apiVersion: v1
kind: Service
metadata:
  name: group-service
  namespace: group-service
spec:
  selector:
    app: group-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
