apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  namespace: quiz-service
spec:
  selector:
    app: quiz-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
