apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kong
  name: kong-declarative-config
data:
  kong.yml: |
    _format_version: "3.0"
    services:
      - name: example-service
        url: http://example.com
        routes:
          - name: example-route
            paths:
              - /
      - name: user-service
        url: http://user-service.user-service.svc.cluster.local:8080
        routes:
          - name: user-route
            paths:
              - /user
      - name : report-service
        url: http://report-service.report-service.svc.cluster.local:8080
        routes:
          - name: report-route
            paths:
              - /report
      - name: quiz-service
        url: http://quiz-service.quiz-service.svc.cluster.local:8080
        routes:
          - name: quiz-route
            paths:
              - /quiz
      - name: expert-service
        url: http://expert-service.expert-service.svc.cluster.local:8080
        routes:
          - name: expert-route
            paths:
              - /expert
      - name: post-service
        url: http://post-service.post-service.svc.cluster.local:8080
        routes:
          - name: post-route
            paths:
              - /post
      - name: notification-service
        url: http://notification-service.notification-service.svc.cluster.local:8080
        routes:
          - name: notification-route
            paths:
              - /notification
      - name: detector-service
        url: http://detector-service.detector-service.svc.cluster.local:5000
        routes:
          - name: detector-route
            paths:
              - /detector
      - name: group-service
        url: http://group-service.group-service.svc.cluster.local:8080
        routes:
          - name: group-route
            paths:
              - /group  
      - name: payment-service
        url: http://payment-service.payment-service.svc.cluster.local:8080
        routes:
          - name: payment-route
            paths:
              - /payment  
      - name : chat-service
        url: http://chat-service.chat-service.svc.cluster.local:8080
        routes:
          - name: chat-route
            paths:
              - /chat 
        connect_timeout: 3600000
