apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kong
  name: kong-gateway
  labels:
    app: kong-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-gateway
  template:
    metadata:
      labels:
        app: kong-gateway
    spec:
      containers:
        - name: kong
          image: kong:latest
          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
            - containerPort: 8002
            - containerPort: 8444
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu : "100m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "200m"
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: "/etc/kong/kong.yml"
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
              
            # Đổi IP này thành IP của máy bạn hoăc IP của LoadBalancer để có service trong GUI
            - name: KONG_ADMIN_GUI_URL
              value: "http://10.97.29.82:8002"
          volumeMounts:
            - name: kong-config
              mountPath: /etc/kong/kong.yml
              subPath: kong.yml
      volumes:
        - name: kong-config
          configMap:
            name: kong-declarative-config
