version: '1.0'
services:
  # 1
  user-service:
    image: healingcommunity/user-service:latest
    container_name: user-service
    ports:
      - "80:8080" # API exposed at port 80
    networks:
      - app-network
  # 2
  group-service:
    image: healingcommunity/group-service:latest
    container_name: group-service
    ports:
      - "81:8080"  # API exposed at port 81
      - "6005:5005"  # gRPC exposed at port 50
    networks:
      - app-network
  # 3
  post-service:
    image: healingcommunity/post-service:latest
    container_name: post-service
    ports:
      - "82:8080"  # API exposed at port 82
    networks:
      - app-network
  # 4
  payment-service:
    image: healingcommunity/payment-service:latest
    container_name: payment-service
    ports:
      - "83:8080"  # API exposed at port 83
    networks:
      - app-network
  # 5
  notification-service:
    image: healingcommunity/notification-service:latest
    container_name: notification-service
    ports:
      - "84:8080"  # API exposed at port 84
    networks:
      - app-network
  # 6
  chat-service:
    image: healingcommunity/chat-service:latest
    container_name: chat-service
    ports:
      - "85:8080"  # API exposed at port 85
    networks:
      - app-network
  # 7
  expert-service:
    image: healingcommunity/expert-service:latest
    container_name: expert-service
    ports:
      - "86:8080"  # API exposed at port 86
      - "5005:5005"  # gRPC exposed at port 50
    networks:
      - app-network
  # 8
  detector-service:
    image: healingcommunity/detector-service:latest
    container_name: detector-service
    ports:
      - "8087:5000"  # API exposed at port 87
      # - "50:5005"  # gRPC exposed at port 50
    networks:
      - app-network

  # 9
  quiz-service:
    image: healingcommunity/quiz-service:latest
    container_name: quiz-service
    ports:
      - "88:8080"  # API exposed at port 88
    networks:
      - app-network
  # 10
  report-service:
    image: healingcommunity/report-service:latest
    container_name: report-service
    ports:
      - "89:8080"  # API exposed at port 89
    networks:
      - app-network
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"  # RabbitMQ exposed at port 15672
      - "5672:5672"  # RabbitMQ exposed at port 5672
    networks:
      - app-network
  

  kong-database:
    image: postgres:latest
    restart: unless-stopped
    networks:
      - app-network
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    ports:
      - "5432:5432"

  kong-migration:
    image: kong:latest
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    networks:
      - app-network
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpass
    restart: on-failure

  kong-gateway:
    image: kong:latest
    restart: unless-stopped
    networks:
      - app-network
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8002:8002"
      - "8444:8444"
    depends_on:
      - kong-migration
      - kong-database
    extra_hosts:
      - "host.docker.internal:host-gateway"
# Initialize Kong with some services and routes
  kong-init:
    image: curlimages/curl:latest
    command: >
      sh -c "
        sleep 10 &&
        curl -i -X POST http://kong-gateway:8001/services --data name=user-service --data url=http://user-service:8080 &&
        curl -i -X POST http://kong-gateway:8001/services/user-service/routes --data paths[]=/user &&

        curl -i -X POST http://kong-gateway:8001/services --data name=group-service --data url=http://group-service:8080 &&
        curl -i -X POST http://kong-gateway:8001/services/group-service/routes --data paths[]=/group &&

        curl -i -X POST http://kong-gateway:8001/services --data name=post-service --data url=http://post-service:8080 &&
        curl -i -X POST http://kong-gateway:8001/services/post-service/routes --data paths[]=/post &&

        curl -i -X POST http://kong-gateway:8001/services --data name=payment-service --data url=http://payment-service:8080 &&
        curl -i -X POST http://kong-gateway:8001/services/payment-service/routes --data paths[]=/payment &&
        
        curl -i -X POST http://kong-gateway:8001/services --data name=notification-service --data url=http://notification-service:8080 &&
        curl -i -X POST http://kong-gateway:8001/services/notification-service/routes --data paths[]=/notification &&
        
        curl -i -X POST http://kong-gateway:8001/services --data name=chat-service --data url=http://chat-service:8080 &&
        curl -i -X POST http://kong-gateway:8001/services/chat-service/routes --data paths[]=/chat &&
        
        curl -i -X POST http://kong-gateway:8001/services --data name=expert-service --data url=http://expert-service:8080 &&
        curl -i -X POST http://kong-gateway:8001/services/expert-service/routes --data paths[]=/expert &&
        
        curl -i -X POST http://kong-gateway:8001/services --data name=detector-service --data url=http://detector-service:5000 &&
        curl -i -X POST http://kong-gateway:8001/services/detector-service/routes --data paths[]=/detector &&
        
        curl -i -X POST http://kong-gateway:8001/services --data name=quiz-service --data url=http://quiz-service:8080 &&
        curl -i -X POST http://kong-gateway:8001/services/quiz-service/routes --data paths[]=/quiz &&
        
        curl -i -X POST http://kong-gateway:8001/services --data name=report-service --data url=http://report-service:8080 &&
        curl -i -X POST http://kong-gateway:8001/services/report-service/routes --data paths[]=/report
      "
    depends_on:
      - kong-gateway
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
