apiVersion: v1
kind: Service
metadata:
  name: expert-service
  namespace: expert-service
spec:
  selector:
    app: expert-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 5005
      targetPort: 5005
  type: ClusterIP
