apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: report-service
  labels:
    app: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
        - name: report-service
          image: healingcommunity/report-service:latest
          ports:
            - containerPort: 8080
          # livenessProbe:
          #   httpGet:
          #     path: /health/liveness
          #     port: 8080
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
          # readinessProbe:
          #   httpGet:
          #     path: /health/readiness
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
      volumes:
        - name: config-volume
          configMap:
            name: appsetting-config
