apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: report-service
  labels:
    app: report-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
      - name: report-service
        image: healingcommunity/report-service:latest
        ports:
        - containerPort: 8080
        # livenessProbe:
        #   httpGet:
        #     path: /health/liveness
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # readinessProbe:
        #   httpGet:
        #     path: /health/readiness
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
