apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: report-service
spec:
  selector:
    app: report-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
