apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'user-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['user-service.default.svc.cluster.local:8080']

      - job_name: 'quizz-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['quizz-service.default.svc.cluster.local:8080']
      
      - job_name: 'post-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['post-service.default.svc.cluster.local:8080']

      - job_name: 'expert-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['expert-service.default.svc.cluster.local:8080']
      
      - job_name: 'report-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['report-service.default.svc.cluster.local:8080']
      
      - job_name: 'notification-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['notification-service.default.svc.cluster.local:8080']
