apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service-deployment
  labels:
    app: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
      - name: report-service
        image: healingcommunity/report-service:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: report-service-lb
spec:
  selector:
    app: report-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8080
  type: LoadBalancer
