apiVersion: v1
kind: Service
metadata:
  namespace: kong
  name: kong-gateway
  labels:
    app: kong-gateway
spec:
  type: LoadBalancer
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
    - name: proxy-ssl
      port: 8443
      targetPort: 8443
    - name: admin
      port: 8001
      targetPort: 8001
    - name: admin-gui
      port: 8002
      targetPort: 8002
    - name: admin-ssl
      port: 8444
      targetPort: 8444
  selector:
    app: kong-gateway
